name: 'payments_dbt'
version: '1.0.0'

# Profile name must match your profiles.yml
profile: 'payments_dbt'

# Project file structure
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  payments_dbt:
    +materialized: table   # default for all models unless overridden

    staging:
      +materialized: view  # staging models become views

    marts:
      +materialized: table  # marts (facts/dims) built as tables
